import type { ProductId } from "./constants";

export interface Cut {
  id: string;
  image: string;
  scientificName?: string;
}

export const CUTS: Record<ProductId, Cut[]> = {
  beef: [
    // Primal & sub-primal cuts
    { id: "neck", image: "" },
    { id: "chuck", image: "" },
    { id: "chuck_tender", image: "" },
    { id: "bolar_blade", image: "" },
    { id: "oyster_blade", image: "" },
    { id: "cube_roll", image: "" },
    { id: "striploin", image: "" },
    { id: "tenderloin", image: "" },
    { id: "hump", image: "" },
    { id: "brisket", image: "" },
    { id: "brisket_bone_in", image: "" },
    { id: "flank", image: "" },
    { id: "thin_flank", image: "" },
    { id: "thick_skirt", image: "" },
    { id: "rib_finger", image: "" },
    { id: "topside", image: "" },
    { id: "flat", image: "" },
    { id: "eyeround", image: "" },
    { id: "knuckle", image: "" },
    { id: "cap_of_rump", image: "" },
    { id: "heart_of_rump", image: "" },
    { id: "tail_of_rump", image: "" },
    { id: "shank", image: "" },
    { id: "shin", image: "" },
    { id: "heel_muscle", image: "" },
    // Offals & by-products
    { id: "tongue", image: "" },
    { id: "liver", image: "" },
    { id: "heart", image: "" },
    { id: "kidney", image: "" },
    { id: "brain", image: "" },
    { id: "tail", image: "" },
    { id: "cheek_meat", image: "" },
    { id: "head_meat", image: "" },
    { id: "lips", image: "" },
    { id: "mask", image: "" },
    { id: "lung", image: "" },
    { id: "spleen", image: "" },
    { id: "aorta", image: "" },
    { id: "tendon", image: "" },
    { id: "paddywack", image: "" },
    { id: "spinal_cord", image: "" },
    { id: "brisket_fat", image: "" },
    { id: "membrane", image: "" },
    { id: "sangria", image: "" },
    { id: "gall_bladder", image: "" },
    { id: "honeycomb", image: "" },
    { id: "green_tripe", image: "" },
    { id: "tripe_semi_cooked", image: "" },
    { id: "omasum", image: "" },
    { id: "abomasum", image: "" },
  ],
  pork: [
    // Primal & sub-primal cuts
    { id: "shoulder", image: "" },
    { id: "collar", image: "" },
    { id: "loin_bone_in", image: "" },
    { id: "tenderloin", image: "" },
    { id: "belly", image: "" },
    { id: "leg", image: "" },
    { id: "ribs", image: "" },
    { id: "whole_ribs", image: "" },
    { id: "chop", image: "" },
    { id: "hock", image: "" },
    { id: "jowl", image: "" },
    { id: "front_feet", image: "" },
    { id: "hind_feet", image: "" },
    { id: "skin", image: "" },
    // Bones
    { id: "backbone", image: "" },
    { id: "neck_bone", image: "" },
    { id: "femur", image: "" },
    { id: "sternum", image: "" },
    // Offals & by-products
    { id: "head", image: "" },
    { id: "head_meat", image: "" },
    { id: "cheek_meat", image: "" },
    { id: "mask", image: "" },
    { id: "earflaps", image: "" },
    { id: "tongue", image: "" },
    { id: "heart", image: "" },
    { id: "liver", image: "" },
    { id: "kidney", image: "" },
    { id: "stomach", image: "" },
    { id: "large_intestine", image: "" },
    { id: "small_intestine", image: "" },
    { id: "rectum", image: "" },
    { id: "tail", image: "" },
  ],
  poultry: [
    // Whole & major cuts
    { id: "whole_chicken", image: "" },
    { id: "whole_carcass", image: "" },
    { id: "breast", image: "" },
    { id: "breast_fillet", image: "" },
    { id: "thigh", image: "" },
    { id: "drumstick", image: "" },
    { id: "leg_quarter", image: "" },
    { id: "whole_leg", image: "" },
    { id: "wings", image: "" },
    { id: "drumette", image: "" },
    { id: "mid_joint", image: "" },
    { id: "wing_tip", image: "" },
    { id: "upper_back", image: "" },
    { id: "neck", image: "" },
    { id: "shanks", image: "" },
    { id: "feet", image: "" },
    { id: "skin", image: "" },
    { id: "mdm", image: "" },
    // Hen products
    { id: "whole_hen", image: "" },
    { id: "hen_leg_quarter", image: "" },
    { id: "hen_wings", image: "" },
    { id: "hen_feet", image: "" },
    { id: "hen_comb", image: "" },
    // Offals
    { id: "heart", image: "" },
    { id: "liver", image: "" },
    { id: "gizzard", image: "" },
    { id: "tail", image: "" },
  ],
  fish: [
    // Salmon products
    { id: "salmon_whole_round", image: "", scientificName: "Salmo salar" },
    { id: "salmon_bellies", image: "", scientificName: "Salmo salar" },
    { id: "salmon_head", image: "", scientificName: "Salmo salar" },
    { id: "salmon_black_bones", image: "", scientificName: "Salmo salar" },
    // Whole fish species
    { id: "hake_gayi", image: "", scientificName: "Merluccius gayi" },
    { id: "mahi_mahi", image: "", scientificName: "Coryphaena hippurus" },
    { id: "catfish", image: "", scientificName: "Pangasius hypophthalmus" },
    { id: "seatrout", image: "", scientificName: "Cynoscion guatucupa" },
    { id: "king_weakfish", image: "", scientificName: "Macrodon ancylodon" },
    { id: "capelin", image: "", scientificName: "Mallotus villosus" },
    { id: "golden_carp", image: "", scientificName: "Carassius auratus" },
    { id: "liza", image: "", scientificName: "Mugil liza" },
    { id: "saraca", image: "", scientificName: "Brevoortia aurea" },
    { id: "shad_fish", image: "", scientificName: "Prochilodus platensis" },
    { id: "bullet_tuna", image: "", scientificName: "Auxis rochei" },
    { id: "red_porgy", image: "", scientificName: "Pagrus pagrus" },
    { id: "peruvian_anchoveta", image: "", scientificName: "Engraulis ringens" },
    { id: "black_croaker", image: "", scientificName: "Pogonias cromis" },
    { id: "white_croaker", image: "", scientificName: "Micropogonias furnieri" },
    { id: "yellow_croaker", image: "", scientificName: "Larimichthys polyactis" },
  ],
  lamb: [
    { id: "rack", image: "" },
    { id: "leg", image: "" },
    { id: "shoulder", image: "" },
    { id: "loin", image: "" },
    { id: "shank", image: "" },
    { id: "chops", image: "" },
  ],
  goat: [
    { id: "leg", image: "" },
    { id: "shoulder", image: "" },
    { id: "rack", image: "" },
    { id: "loin", image: "" },
    { id: "shank", image: "" },
  ],
  buffalo: [
    { id: "ribeye", image: "" },
    { id: "striploin", image: "" },
    { id: "tenderloin", image: "" },
    { id: "brisket", image: "" },
    { id: "rump", image: "" },
    { id: "shank", image: "" },
  ],
  turkey: [
    { id: "whole", image: "" },
    { id: "breast", image: "" },
    { id: "thigh", image: "" },
    { id: "drumstick", image: "" },
    { id: "wing", image: "" },
  ],
};
