import type { ProductId } from "./constants";

export interface Cut {
  id: string;
  image: string;
  scientificName?: string;
}

export const CUTS: Record<ProductId, Cut[]> = {
  beef: [
    // Primal & sub-primal cuts
    { id: "neck", image: "/products/cuts/beef/neck.jpg" },
    { id: "chuck", image: "/products/cuts/beef/chuck.jpg" },
    { id: "chuck_tender", image: "/products/cuts/beef/chuck_tender.jpg" },
    { id: "bolar_blade", image: "/products/cuts/beef/bolar_blade.jpg" },
    { id: "oyster_blade", image: "/products/cuts/beef/oyster_blade.jpg" },
    { id: "cube_roll", image: "/products/cuts/beef/cube_roll.jpg" },
    { id: "striploin", image: "/products/cuts/beef/striploin.jpg" },
    { id: "tenderloin", image: "/products/cuts/beef/tenderloin.jpg" },
    { id: "hump", image: "/products/cuts/beef/hump.jpg" },
    { id: "brisket", image: "/products/cuts/beef/brisket.jpg" },
    { id: "brisket_bone_in", image: "/products/cuts/beef/brisket_bone_in.jpg" },
    { id: "flank", image: "/products/cuts/beef/flank.jpg" },
    { id: "thin_flank", image: "/products/cuts/beef/thin_flank.jpg" },
    { id: "thick_skirt", image: "/products/cuts/beef/thick_skirt.jpg" },
    { id: "rib_finger", image: "/products/cuts/beef/rib_finger.jpg" },
    { id: "topside", image: "/products/cuts/beef/topside.jpg" },
    { id: "flat", image: "/products/cuts/beef/flat.jpg" },
    { id: "eyeround", image: "/products/cuts/beef/eyeround.jpg" },
    { id: "knuckle", image: "/products/cuts/beef/knuckle.jpg" },
    { id: "cap_of_rump", image: "/products/cuts/beef/cap_of_rump.jpg" },
    { id: "heart_of_rump", image: "/products/cuts/beef/heart_of_rump.jpg" },
    { id: "tail_of_rump", image: "/products/cuts/beef/tail_of_rump.jpg" },
    { id: "shank", image: "/products/cuts/beef/shank.jpg" },
    { id: "shin", image: "/products/cuts/beef/shin.jpg" },
    { id: "heel_muscle", image: "/products/cuts/beef/heel_muscle.jpg" },
    // Offals & by-products
    { id: "tongue", image: "/products/cuts/beef/tongue.jpg" },
    { id: "liver", image: "/products/cuts/beef/liver.jpg" },
    { id: "heart", image: "/products/cuts/beef/heart.jpg" },
    { id: "kidney", image: "/products/cuts/beef/kidney.jpg" },
    { id: "brain", image: "/products/cuts/beef/brain.jpg" },
    { id: "tail", image: "/products/cuts/beef/tail.jpg" },
    { id: "cheek_meat", image: "/products/cuts/beef/cheek_meat.jpg" },
    { id: "head_meat", image: "/products/cuts/beef/head_meat.jpg" },
    { id: "lips", image: "/products/cuts/beef/lips.jpg" },
    { id: "mask", image: "/products/cuts/beef/mask.jpg" },
    { id: "lung", image: "/products/cuts/beef/lung.jpg" },
    { id: "spleen", image: "/products/cuts/beef/spleen.jpg" },
    { id: "aorta", image: "/products/cuts/beef/aorta.jpg" },
    { id: "tendon", image: "/products/cuts/beef/tendon.jpg" },
    { id: "paddywack", image: "/products/cuts/beef/paddywack.jpg" },
    { id: "spinal_cord", image: "/products/cuts/beef/spinal_cord.jpg" },
    { id: "brisket_fat", image: "/products/cuts/beef/brisket_fat.jpg" },
    { id: "membrane", image: "/products/cuts/beef/membrane.jpg" },
    { id: "sangria", image: "/products/cuts/beef/sangria.jpg" },
    { id: "gall_bladder", image: "/products/cuts/beef/gall_bladder.jpg" },
    { id: "honeycomb", image: "/products/cuts/beef/honeycomb.jpg" },
    { id: "green_tripe", image: "/products/cuts/beef/green_tripe.jpg" },
    { id: "tripe_semi_cooked", image: "/products/cuts/beef/tripe_semi_cooked.jpg" },
    { id: "omasum", image: "/products/cuts/beef/omasum.jpg" },
    { id: "abomasum", image: "/products/cuts/beef/abomasum.jpg" },
  ],
  pork: [
    // Primal & sub-primal cuts
    { id: "shoulder", image: "/products/cuts/pork/shoulder.jpg" },
    { id: "collar", image: "/products/cuts/pork/collar.jpg" },
    { id: "loin_bone_in", image: "/products/cuts/pork/loin_bone_in.jpg" },
    { id: "tenderloin", image: "/products/cuts/pork/tenderloin.jpg" },
    { id: "belly", image: "/products/cuts/pork/belly.jpg" },
    { id: "leg", image: "/products/cuts/pork/leg.jpg" },
    { id: "ribs", image: "/products/cuts/pork/ribs.jpg" },
    { id: "whole_ribs", image: "/products/cuts/pork/whole_ribs.jpg" },
    { id: "chop", image: "/products/cuts/pork/chop.jpg" },
    { id: "hock", image: "/products/cuts/pork/hock.jpg" },
    { id: "jowl", image: "/products/cuts/pork/jowl.jpg" },
    { id: "front_feet", image: "/products/cuts/pork/front_feet.jpg" },
    { id: "hind_feet", image: "/products/cuts/pork/hind_feet.jpg" },
    { id: "skin", image: "/products/cuts/pork/skin.jpg" },
    // Bones
    { id: "backbone", image: "/products/cuts/pork/backbone.jpg" },
    { id: "neck_bone", image: "/products/cuts/pork/neck_bone.jpg" },
    { id: "femur", image: "/products/cuts/pork/femur.jpg" },
    { id: "sternum", image: "/products/cuts/pork/sternum.jpg" },
    // Offals & by-products
    { id: "head", image: "/products/cuts/pork/head.jpg" },
    { id: "head_meat", image: "/products/cuts/pork/head_meat.jpg" },
    { id: "cheek_meat", image: "/products/cuts/pork/cheek_meat.jpg" },
    { id: "mask", image: "/products/cuts/pork/mask.jpg" },
    { id: "earflaps", image: "/products/cuts/pork/earflaps.jpg" },
    { id: "tongue", image: "/products/cuts/pork/tongue.jpg" },
    { id: "heart", image: "/products/cuts/pork/heart.jpg" },
    { id: "liver", image: "/products/cuts/pork/liver.jpg" },
    { id: "kidney", image: "/products/cuts/pork/kidney.jpg" },
    { id: "stomach", image: "/products/cuts/pork/stomach.jpg" },
    { id: "large_intestine", image: "/products/cuts/pork/large_intestine.jpg" },
    { id: "small_intestine", image: "/products/cuts/pork/small_intestine.jpg" },
    { id: "rectum", image: "/products/cuts/pork/rectum.jpg" },
    { id: "tail", image: "/products/cuts/pork/tail.jpg" },
  ],
  poultry: [
    // Whole & major cuts
    { id: "whole_chicken", image: "/products/cuts/poultry/whole_chicken.jpg" },
    { id: "whole_carcass", image: "/products/cuts/poultry/whole_carcass.jpg" },
    { id: "breast", image: "/products/cuts/poultry/breast.jpg" },
    { id: "breast_fillet", image: "/products/cuts/poultry/breast_fillet.jpg" },
    { id: "thigh", image: "/products/cuts/poultry/thigh.jpg" },
    { id: "drumstick", image: "/products/cuts/poultry/drumstick.jpg" },
    { id: "leg_quarter", image: "/products/cuts/poultry/leg_quarter.jpg" },
    { id: "whole_leg", image: "/products/cuts/poultry/whole_leg.jpg" },
    { id: "wings", image: "/products/cuts/poultry/wings.jpg" },
    { id: "drumette", image: "/products/cuts/poultry/drumette.jpg" },
    { id: "mid_joint", image: "/products/cuts/poultry/mid_joint.jpg" },
    { id: "wing_tip", image: "/products/cuts/poultry/wing_tip.jpg" },
    { id: "upper_back", image: "/products/cuts/poultry/upper_back.jpg" },
    { id: "neck", image: "/products/cuts/poultry/neck.jpg" },
    { id: "shanks", image: "/products/cuts/poultry/shanks.jpg" },
    { id: "feet", image: "/products/cuts/poultry/feet.jpg" },
    { id: "skin", image: "/products/cuts/poultry/skin.jpg" },
    { id: "mdm", image: "/products/cuts/poultry/mdm.jpg" },
    // Hen products
    { id: "whole_hen", image: "/products/cuts/poultry/whole_hen.jpg" },
    { id: "hen_leg_quarter", image: "/products/cuts/poultry/hen_leg_quarter.jpg" },
    { id: "hen_wings", image: "/products/cuts/poultry/hen_wings.jpg" },
    { id: "hen_feet", image: "/products/cuts/poultry/hen_feet.jpg" },
    { id: "hen_comb", image: "/products/cuts/poultry/hen_comb.jpg" },
    // Offals
    { id: "heart", image: "/products/cuts/poultry/heart.jpg" },
    { id: "liver", image: "/products/cuts/poultry/liver.jpg" },
    { id: "gizzard", image: "/products/cuts/poultry/gizzard.jpg" },
    { id: "tail", image: "/products/cuts/poultry/tail.jpg" },
  ],
  fish: [
    // Salmon products
    { id: "salmon_whole_round", image: "/products/cuts/fish/salmon_whole_round.jpg", scientificName: "Salmo salar" },
    { id: "salmon_bellies", image: "/products/cuts/fish/salmon_bellies.jpg", scientificName: "Salmo salar" },
    { id: "salmon_head", image: "/products/cuts/fish/salmon_head.jpg", scientificName: "Salmo salar" },
    { id: "salmon_black_bones", image: "/products/cuts/fish/salmon_black_bones.jpg", scientificName: "Salmo salar" },
    // Whole fish species
    { id: "hake_gayi", image: "/products/cuts/fish/hake_gayi.jpg", scientificName: "Merluccius gayi" },
    { id: "mahi_mahi", image: "/products/cuts/fish/mahi_mahi.jpg", scientificName: "Coryphaena hippurus" },
    { id: "catfish", image: "/products/cuts/fish/catfish.jpg", scientificName: "Pangasius hypophthalmus" },
    { id: "seatrout", image: "/products/cuts/fish/seatrout.jpg", scientificName: "Cynoscion guatucupa" },
    { id: "king_weakfish", image: "/products/cuts/fish/king_weakfish.jpg", scientificName: "Macrodon ancylodon" },
    { id: "capelin", image: "/products/cuts/fish/capelin.jpg", scientificName: "Mallotus villosus" },
    { id: "golden_carp", image: "/products/cuts/fish/golden_carp.jpg", scientificName: "Carassius auratus" },
    { id: "liza", image: "/products/cuts/fish/liza.jpg", scientificName: "Mugil liza" },
    { id: "saraca", image: "/products/cuts/fish/saraca.jpg", scientificName: "Brevoortia aurea" },
    { id: "shad_fish", image: "/products/cuts/fish/shad_fish.jpg", scientificName: "Prochilodus platensis" },
    { id: "bullet_tuna", image: "/products/cuts/fish/bullet_tuna.jpg", scientificName: "Auxis rochei" },
    { id: "red_porgy", image: "/products/cuts/fish/red_porgy.jpg", scientificName: "Pagrus pagrus" },
    { id: "peruvian_anchoveta", image: "/products/cuts/fish/peruvian_anchoveta.jpg", scientificName: "Engraulis ringens" },
    { id: "black_croaker", image: "/products/cuts/fish/black_croaker.jpg", scientificName: "Pogonias cromis" },
    { id: "white_croaker", image: "/products/cuts/fish/white_croaker.jpg", scientificName: "Micropogonias furnieri" },
    { id: "yellow_croaker", image: "/products/cuts/fish/yellow_croaker.jpg", scientificName: "Larimichthys polyactis" },
  ],
  lamb: [
    { id: "rack", image: "/products/cuts/lamb/rack.png" },
    { id: "leg", image: "/products/cuts/lamb/leg.png" },
    { id: "shoulder", image: "/products/cuts/lamb/shoulder.png" },
    { id: "loin", image: "/products/cuts/lamb/loin.png" },
    { id: "shank", image: "/products/cuts/lamb/shank.png" },
    { id: "chops", image: "/products/cuts/lamb/chops.png" },
  ],
  goat: [
    { id: "leg", image: "/products/cuts/goat/leg.png" },
    { id: "shoulder", image: "/products/cuts/goat/shoulder.png" },
    { id: "rack", image: "/products/cuts/goat/rack.png" },
    { id: "loin", image: "/products/cuts/goat/loin.png" },
    { id: "shank", image: "/products/cuts/goat/shank.png" },
  ],
  buffalo: [
    { id: "ribeye", image: "/products/cuts/buffalo/ribeye.png" },
    { id: "striploin", image: "/products/cuts/buffalo/striploin.png" },
    { id: "tenderloin", image: "/products/cuts/buffalo/tenderloin.png" },
    { id: "brisket", image: "/products/cuts/buffalo/brisket.png" },
    { id: "rump", image: "/products/cuts/buffalo/rump.png" },
    { id: "shank", image: "/products/cuts/buffalo/shank.png" },
  ],
  turkey: [
    { id: "whole", image: "/products/cuts/turkey/whole.png" },
    { id: "breast", image: "/products/cuts/turkey/breast.png" },
    { id: "thigh", image: "/products/cuts/turkey/thigh.png" },
    { id: "drumstick", image: "/products/cuts/turkey/drumstick.png" },
    { id: "wing", image: "/products/cuts/turkey/wing.png" },
  ],
};
